Pull Request: Up-And-Running Supervised Training Example
EtienneChollet/cassetta pull request #3
Opened 2024-10-04 00:00 UTC by EtienneChollet

# Pull Request: Up-And-Running Supervised Training Example

# **Overview**
This PR introduces enhancements and new features, focusing on backbone models, I/O modules, optimizers, loss functions, datasets, and documentation - and generally, **getting everything up and running for some basic supervised training**!

# **Changes Summary**

## 1. **Backbone Models Enhancements**
   
   - **`cassetta/backbones/fcn.py`**
     - **Overwrite `nb_levels`:** Now, if a user defines a list of the number of features per level (`feat_list`), any predefined `nb_levels` will be overwritten.
     - **Purpose:** Provides greater flexibility in configuring the FCN backbone by allowing users to customize features/levels without being constrained by preset values or running into errors because of them (when `len(feat_list) != nb_levels`).

   - **`cassetta/backbones/unet.py`**
     - **`UNet`Inherits from `LoadableMixin`:** The UNet backbone is now loadable by inheriting from the `LoadableMixin` class.
     - **Purpose:** Enhances the `UNet` backbone by enabling easy serialization and deserialization.

## 2. **I/O Modules Improvements**
   
   - **`cassetta/io/modules.py`**
     - **Helper Functions for Module Validation:**
       - **Added Functions:** Validate if module(s) are loadable to preemptively check for potential issues.
       - **Purpose:** Ensures that modules can be reliably loaded, preventing runtime errors related to module loading.
     - **`StateMixin` Class:**
       - **Added:** Handles saving and loading the state of data containers in multiple file formats **(`yaml`, `json`, `pt`)**.
       - **Purpose:** Provides a standardized way to save the state of various data containers, enhancing flexibility and ease of use.
     - **Expanded on Loadable Containers:**
       - **Classes Expanded:** `LoadableSequential`, `LoadableModuleList`, and `LoadableModuleDict`.
       - **Note:** Should I avoid redefining the `serialize()` methods for each class to maintain consistency and reduce redundancy? I think we said I _should_ avoid that. 
     - **Code Formatting:**
       - **Applied:** Reformatted the module using `black`.
       - **Note:** Reverting this change is planned if necessary to maintain code style consistency.

## 3. **Utility Functions Addition**
   
   - **`cassetta/core/utils.py`**
     - **Added Helper Functions:**
       - **Refreshing Experiment Directory:** Deletes old files (if, for example, erasing a model and re-training it is desired).
       - **Deleting Files by Pattern:** Removes all files matching a specific pattern.
       - **Finding Files by Pattern:** Locates all files that match a certain pattern.
     - **Purpose:** Streamlines experiment management by providing utilities for directory and file handling, mostly for checkpointing and housekeeping.

## 4. **Dataset Module Addition**
   
   - **`cassetta/datasets/supervised.py`**
     - **Added Module:** Generates random x-y pairs of data for supervised learning.
     - **Purpose:** Introduces a way to generate data to sanity check training pipelines using paired input-output data.

## 5. **Loss Functions Enhancements**
   
   - **`cassetta/losses/regression.py`**
     - **Added `LoadableMSE`:** A regression loss function based on Mean Squared Error (MSE) that is loadable.
     - **Purpose:** Provides a simple loadable MSE loss function for regression tasks, ensuring consistency and ease of use.

## 6. **Optimizers Enhancements**
   
   - **`cassetta/optimizers/adam.py`**
     - **Added `LoadableAdam`:** An Adam optimizer that is loadable.
     - **Purpose:** Enhances the optimizer's interoperability within the framework, allowing for easy saving and loading of the optimizer.

## 7. **Documentation and Examples**
   
   - **`docs/examples/supervised-segmentation.ipynb`**
     - **Added Demo Notebook:** Demonstrates supervised segmentation using the updated framework.
     - **Purpose:** Provides users with a practical example of how to implement supervised segmentation, aiding in understanding and adoption of the new features.

# **TODO**
- @EtienneChollet will reformat `cassetta/io/modules.py` to revert to state before running `black`.
- Specific questions for @balbasty
   - `cassetta/io/modules.py`: Should I avoid redefining the `serialize()` method within `Loadable*`
   - `docs/examples/supervised-segmentation.ipynb`: Is the Jupyter notebook example sufficient for the example of supervised segmentation?
   - You said it would be cool to be able to make anything (like optimizers and loss functions) loadable.

# **Motivation**
The enhancements in this PR address the need for an up-and-running supervised segmentation framework. By making backbone models loadable, adding practical I/O utilities, introducing loadable optimizers and loss functions, and adding sanitychecking dataset, we aim to streamline the model training process. The inclusion of a demo notebook facilitates better understanding and quicker onboarding for users.

# **Conclusion**
This enhances `cassetta` by adding more loadable components, expanding utility functions, adding support for supervised datasets, and building an up-and-running supervised segmentation example.
---

2024-10-04 08:59 UTC, balbasty reviewed
I still have a couple of things to go through but this will get us started.

Let me know if you want to meet sometime next week to iron it out!

2024-10-04 08:59 UTC, balbasty commented on cassetta/backbones/unet.py
> +from cassetta.io.modules import LoadableMixin
Can you move this one line up so that local imports appear after general imports?

I try do do this order in general:
```python
# 1. standard/dependency module imports
import re
import sys
import torch
# 2. standard module import with `import from` form
from typing import Optional
# 3. general cassetta imports
from cassetta.io.modules import LoadableMixin
# 4. local imports
from .fcn import ConvEncoder
```

2024-10-04 08:59 UTC, balbasty commented on cassetta/backbones/unet.py
> +class UNet(nn.Module, LoadableMixin):
Mixins should be to the left (it's because of how method resolution works when methods exist in multiple bases)

```python
class UNet(LoadableMixin, nn.Module): ...
```

Also, should we make all backbones loadable then?

2024-10-04 08:59 UTC, balbasty commented on cassetta/datasets/supervised.py
> +                 ):
Personal style preference (😋), I prefer

```python
def __init__(self,
    n_samples: str = 100,
    x_shape: tuple = (1, 64, 64, 64),
    y_shape: tuple = (1, 64, 64, 64),
    n_classes: int = None,
    device: str = 'cuda',
):
```
so that the level of indentation does not depend on the function name.

2024-10-04 08:59 UTC, balbasty commented on cassetta/datasets/supervised.py
> +class SupervisedSanitycheckDataset(Dataset):
Maybe `DummySupervisedDataset` ? So that it's clear fron the start that it's not a real one.

2024-10-04 08:59 UTC, balbasty commented on cassetta/losses/regression.py
> +    [`torch.nn`][`torch.nn.MSELoss`]
Fix Adam -> MSE

2024-10-04 08:59 UTC, balbasty commented on cassetta/losses/__init__.py
>  ], __name__, __all__, True)
I had forgotten about this function. We should probably use this everywhere instead of 
```python
from . import mysubmodule
from .mysubmodule import *
```

2024-10-04 08:59 UTC, balbasty commented on cassetta/optimizers/__init__.py
> +from .adam import *
use `import_submodules`?

2024-10-04 08:59 UTC, balbasty commented on cassetta/datasets/__init__.py
> +from .supervised import *
use `import_submodules`?

2024-10-04 08:59 UTC, balbasty commented on cassetta/optimizers/adam.py
> +                 weight_decay=0, amsgrad=False):
1. **Most important remark**

We need a dedicated LoadableMixin for optimizers because we **do not want** to save `params`. As I've said before (I think), optimizers must always be re-instantiated and passed the _current_ model weights on load.

I think we need a optimizer-specific mechanism.

2. **Less important point, and whichever mechanism we decide on** 

The new Adam has even more parameters no? Like `differentiable` and such? Maybe you can just wrap all parameters without rewriting them?

```python
@LoadableMixin.save_args
def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
```

2024-10-04 08:59 UTC, balbasty commented on cassetta/training/trainers.py
> +@dataclass
two empty lines before a class

2024-10-04 08:59 UTC, balbasty commented on cassetta/training/trainers.py
> +    best_eval_loss: float = 100  # Arbitrary
Is it so that it's a very large value? Then use `float('inf')`

2024-10-04 08:59 UTC, balbasty commented on cassetta/training/trainers.py
> +            }
This might already be in `state`, since `model` is now a `LoadableModule`. Can you check? If it's the case, this bit is unneeded/redundant.

2024-10-04 08:59 UTC, balbasty commented on cassetta/training/trainers.py
> +            obj.optimizers[name] = optimizer
This is where I think we should point to te new loaded weights. Otherwise the weights that are optimized and the model weights are decoupled

2024-10-04 08:59 UTC, balbasty commented on cassetta/training/trainers.py
> +
I would just use the `LoadableMixin logic here`. 

```python
obj = super().load(cls, state)
```

and then add the optimizer/trainerstate specific logic

2024-10-04 08:59 UTC, balbasty commented on cassetta/training/trainers.py
> +        models_state = state.get("models", {})
I'd think models will already be handled by the `Loadable` logic from before, so no need to implement it specifically.

2024-10-04 08:59 UTC, balbasty commented on cassetta/training/trainers.py
> +        params = {}
This is where you fix the optimizer's `params` ! Sorry I had missed it. Where is is used?

2024-10-04 08:59 UTC, balbasty commented on cassetta/training/trainers.py
> +        # instantiate and register loss
Since this trainer assumes a single model, single loss, simgle optimizers, I would define properties to points to these. It will make the BasicSupervisedTrainer code a bit nicer to read.

```python
@property
def model(self):
    return self.models["model"]

@property
def optimizer(self):
    return self.optimizers["model"]

@property
def loss(self):
    return self.losses["model"]
```

And later you can have

```python
  def train_step(self, minibatch):
      # Unpack minibatch
      x, y = minibatch
      # Zero optimizer gradients
      self.optimizer.zero_grad()
      # Forward pass
      outputs = self.model(x)
      # Calculate loss
      _loss = self.loss(y, outputs)
      # Update trainer state
      self.trainer_state.epoch_train_loss += _loss.item()
      # Optionally log.
      # TODO: incorporate logger
      if self.trainer_config.logging:
          self.log_metric('train', _loss.item())
      # Backward pass
      _loss.backward()
      # Step optimizer
      self.optimizer.step()
      # Increment current step
      self.trainer_state.current_step += 1
```

2024-10-04 13:24 UTC, EtienneChollet commented on cassetta/losses/regression.py
> +    [`torch.nn`][`torch.nn.MSELoss`]
Ahh yes, you've caught me copying and pasting from the Adam optimizer 😂. It's fixed now :)

2024-10-04 13:36 UTC, EtienneChollet commented on cassetta/datasets/supervised.py
> +                 ):
Ahh I see. I've resolved this in f2ab5faea2d95ecc7d143c705ed6a0eebf1f2edb

2024-10-04 13:43 UTC, EtienneChollet commented on cassetta/backbones/unet.py
> +class UNet(nn.Module, LoadableMixin):
First comment resolved in d2487fc66a19f72600e59af94ebb8235a98df070

2024-10-04 13:52 UTC, EtienneChollet commented on cassetta/backbones/unet.py
> +class UNet(nn.Module, LoadableMixin):
Hmm - I do think we should make all backbones loadable. Perhaps I'm not understanding the question correctly, or I have a misunderstanding of this specific part of cassetta, but PyTorch doesn't natively save the architecture (levels, features per level, res connections) of the backbone, so it is impossible to load weights from the checkpoint without having the exact architecture already defined somewhere. 

Allowing all backbones to be loadable will permit the user to simply load the trainer (and, thus, backbone) in the same configuration every time without having to initialize the backbone manually.

2024-10-04 14:23 UTC, EtienneChollet commented on cassetta/datasets/supervised.py
> +class SupervisedSanitycheckDataset(Dataset):
Good idea. Resolved in 29201df

2024-10-04 14:54 UTC, EtienneChollet commented on cassetta/optimizers/__init__.py
> +from .adam import *
Fixed in 32bfb5e. I also got a bit distracted fixing `cassetta/optimizers/__init__.py` and tried to align it as much as possible with `cassetta/losses/__init__.py`. I _think_ I did it right - how does it look?

2024-10-04 14:59 UTC, EtienneChollet commented on cassetta/losses/__init__.py
>  ], __name__, __all__, True)
Sounds good :)

2024-10-04 15:03 UTC, EtienneChollet commented on cassetta/datasets/__init__.py
> +from .supervised import *
Resolved with a710cc5

2024-10-04 15:05 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +@dataclass
Resolved with afaf43f

2024-10-04 15:07 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +    best_eval_loss: float = 100  # Arbitrary
Good call! Resolved with 4f35abf

2024-10-04 22:03 UTC, EtienneChollet commented on cassetta/optimizers/adam.py
> +                 weight_decay=0, amsgrad=False):
Great ideas.

### Changes
* 1470c56: Introduces a `LoadableOptimizer` to `cassetta/io/modules.py` as an optimizer-specific mixin
* f86e34c: `LoadableAdam` now inherits from `LoadableOptimizer`. Replace constructor expectations with `*args` and `**kwargs`
* 97b5ede: Revisions to `Trainer` allow optimizers (without saved model parameters) to be instantiated with the saved parameters of the model.


### Summary
`LoadableOptimizer` mixin introduced to save optimizer without model params (avoiding redundant saving of params). `LoadableAdam` inherits from it, and `Trainer` revisions allow optimizer instantiation with saved model parameters.

2024-10-13 16:08 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +            }
You're right, the serialization does occur in `LoadableMixin`, but I was thinking that explicitly putting all models into their own container of sorts (the dict which we will assign the key `"models"` in `state` later) will allow easy access to all the models through `state_dict['models']`. I think you wanted to incorporate this kind multi-model (and optimizer) functionality, right?

2024-10-13 16:19 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +            obj.optimizers[name] = optimizer
Resolved with 97b5ede68f78af50a2bfd3727e7e422d28a84ed1, will that be sufficient?

2024-10-18 15:58 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +            }
Trainer specific method for saving

2024-11-04 20:26 UTC, EtienneChollet commented on cassetta/backbones/unet.py
> +class UNet(nn.Module, LoadableMixin):
Okay. Finally fixed in e01a871! Backbones do _not_ inherit from `LoadableMixin`

2024-11-10 21:40 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +
Revised (kind of) with 564618f28eed1a0a169c26c8ba12aff16f27eb53

2024-11-10 21:41 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +            }
Gotcha. Resolved in 564618f28eed1a0a169c26c8ba12aff16f27eb53

2024-11-10 21:41 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +        models_state = state.get("models", {})
Good call. Fixed in 564618f28eed1a0a169c26c8ba12aff16f27eb53

2024-11-11 10:04 UTC, balbasty commented on cassetta/datasets/supervised.py
> +        return x.to(torch.float32), y.to(torch.float32)
I don't understand why you would convert the target to `float32` when. they are integer class indices.

Also, in general, I don't convert explicitly to `float32`, since most generators (`zeros`, `randn`, etc) return tensors with the data type from `get_default_dtype()` already.

Also, if you do want to ensure a dtype, it's better to pass it to the generator directly (`randn(..., dtype=torch.float32)`) as it saves a copy. (this of course would not work for randint -- but again not sure why we should convert an integer label map to floating point)

2024-11-11 10:05 UTC, balbasty commented on cassetta/losses/regression.py
> +        super().__init__()
There are no arguments to this loss, so no need for `@LoadableMixin.save_args` and therefore no need to reimplement the `__init__` altogether.

2024-11-11 10:06 UTC, balbasty commented on cassetta/optimizers/__init__.py
> +], __name__, __all__, True)
Maybe import `base` as well?

Do we have the `make_*` utility in `__init__` or in `base` in the other modules?

2024-11-11 10:09 UTC, balbasty commented on cassetta/optimizers/__init__.py
> +from torch.optim import optimizer
Shouldn't it be the base class `Optimizer` (with capital `O`)?

2024-11-11 10:11 UTC, balbasty commented on cassetta/training/trainers.py
> +        self.losses = {}
Should we use a `LoadableModuleDict` as well?

2024-11-11 10:11 UTC, balbasty commented on cassetta/training/trainers.py
> +            self.losses['model'] = loss
Maybe the default key should be `"main"`

2024-11-11 10:12 UTC, balbasty commented on cassetta/training/trainers.py
> +        state_dict = super().serialize()
What's the point of this if you redefine `state_dict` just below?

2024-11-11 10:13 UTC, balbasty commented on cassetta/training/trainers.py
> +        )
Again, I would just make `losses` a `LoadableModuleDict` -- makes everything simpler.

2024-11-11 10:14 UTC, balbasty commented on cassetta/training/trainers.py
> +        state_dict = self.models.serialize()
Why do we not do `state_dict["models"] = ...` ?

2024-11-11 10:16 UTC, balbasty commented on cassetta/training/trainers.py
> +        obj.models = LoadableMixin.load(state)
Again, should be `state["models"]`

2024-11-11 10:19 UTC, balbasty commented on cassetta/training/trainers.py
> +        obj.trainer_config = TrainerConfig(**state['trainer_config'])
When would `trainer_state` be absent?

And why not use `TrainerState.from_state_dict(...)` ?

2024-11-11 10:20 UTC, balbasty commented on cassetta/training/trainers.py
> +    def optimizers_from_state_dict(self, obj, state_dict: dict):
make private (`_optimizers_from_state_dict`)

2024-11-11 10:27 UTC, balbasty commented on cassetta/training/trainers.py
> +    def __init__(
Do we ever use the saved arguments?

I know I am the one who said we should make it a `LoadableModule` but in the end we do not use the `LoadableModule` logic to serialize it (since we have our own `serialise()` re-implementation. And we are saving arguments that we never re-use. Also, we actually do not (and maybe do not want to) save all input arguments (like, dataloaders and such).

I think in my head we would be doing something a bit like in torch lightning, where for each project/experiment you would write your own trainer class that inherits from `Trainer`. This inherited class would only take serializable inputs (json-like things: (list of) strings and numbers), and you would define "initialization" functions. But maybe this lightning-like trainer can be a different `FlexibleTrainer` that inherits from the base `Trainer`.

Long story short, for now let's rename `Trainer` to `TrainerBase` and let's not make it inherit `LoadableMixin`.

2024-11-11 10:28 UTC, balbasty commented on cassetta/training/trainers.py
> +class BasicSupervisedTrainer(Trainer):
Rename to `SimpleSupervisedTrainer`

2024-11-11 10:29 UTC, balbasty commented on cassetta/training/trainers.py
> +    def get_loaders(self, dataset):
make private: `_get_loaders`

2024-11-11 13:17 UTC, EtienneChollet commented on .gitignore
> +models/version_1/events.out.tfevents.1728070902.darwin.nmr.mgh.harvard.edu.1880647.0
Whoops 😅. Fixed with 9d2202c4b258c0bd3ef107c4817ef2e12332a375

2024-11-11 13:55 UTC, EtienneChollet commented on cassetta/optimizers/__init__.py
> +], __name__, __all__, True)
Gotcha. Added `base` in e137227 & e70a81b.

As for your question regarding the `make_*` utility: We have them in:
* `cassetta/losses/__init__.py`: `make_loss()` (you made this)
* `cassetta/io/modules.py`: `make_loadable()` (you made this)
* `cassetta/layers/*.py`: `make_{activation, attention, conv, dropout, norm}()` (you made these)
* `cassetta/models/__init__.py`: `make_model()` (you made this)
* `cassetta/optimizers/__init__.py`: `make_optimizer()` (I made this [as you know already by this comment])

It seems as though if we are able to put a generalizable `make_*` in the package's `__init__.py`, we do. But some, more specific `make_*`'s need to go inside individual modules, as is the case for the `cassetta/layers/*` modules.

2024-11-11 13:59 UTC, EtienneChollet commented on cassetta/optimizers/__init__.py
> +from torch.optim import optimizer
Good catch! Resolved in e137227 & e70a81b.

2024-11-11 14:06 UTC, EtienneChollet commented on cassetta/losses/regression.py
> +        super().__init__()
What about parameters such as `reduction`? I'll remove this for now, but maybe when we have a loss with more parameters (like dice, tversky, focal, etc...), we might consider using the `LoadableMixin` logic.

Removed `@LoadableMixin.save_args` in 86f1742.

2024-11-11 14:46 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +        self.losses = {}
I think you're referring to `self.losses`, right? If so, I've invoked the fixes in 75f41a3

2024-11-11 14:49 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +        state_dict = super().serialize()
Whoops, I did not even realize this! Good eye! Fixed in 0609c0f.

2024-11-11 14:52 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +            self.losses['model'] = loss
I agree, I was also making myself confused by calling it "model" 😂. Fixed in d02587e

2024-11-11 14:56 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +        )
Ahh yes, the beauty of cassetta! Fixed in 97c4f63

2024-11-11 15:03 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +        state_dict = self.models.serialize()
@balbasty I had actually considered doing this initially, but it looks like all the models will be saved in `state["state"]` using the logic of default cassetta/pytorch. All models/layers/blocks are part of the state dict for the object, just as the state dict for the optimizers contains `betas`, `eps`, `weight_decay`, etc...

If we wanted to do `state_dict["models"]`, (which I did want to do at first) we would have to remove `state_dict["state"]` (or just make it an empty dict). What are your thoughts on this? should we remove `state["state"]` so we can make `state["models"]`?

2024-11-11 15:22 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +    def optimizers_from_state_dict(self, obj, state_dict: dict):
Good call! Fixed in 79f1aa1

2024-11-11 15:28 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +class BasicSupervisedTrainer(Trainer):
Gotcha! Fixed in a5f1b6f

2024-11-11 15:44 UTC, EtienneChollet commented on cassetta/training/trainers.py
> +    def __init__(
You're right, we don't use the saved arguments, but we _do_ use the `LoadableMixin.save()` method when we go to save checkpoints. If `Trainer` does not subclass `Loadable*`, it would require the user to save the model with `torch.save(trainer.serialize(), checkpoint_path)` instead of `trainer.save(checkpoint_path)`. I realize that it's not much of a difference, but keeping the inheritance and running the latter command would mean manually serializing the trainer is one less thing to forget.

I also think it's nice to subclass `LoadableMixin`/`LoadableModule` for the trainer, as it allows us to see the version of cassetta that was used to train. What do you think of this @balbasty

2024-11-11 17:52 UTC, balbasty commented on cassetta/optimizers/__init__.py
> +], __name__, __all__, True)
thanks for checking, let's keep it where they are then :) (mostly in `__init__` except for layers where there are different `make` for different layers)

2024-11-11 17:54 UTC, balbasty commented on cassetta/training/trainers.py
> +        state_dict = self.models.serialize()
Ok I think this goes hand-in-hand with whether the trainer should be a `LoadableMixin` (which I am tending more and more towards "should not be")

2024-11-11 18:05 UTC, balbasty commented on cassetta/training/trainers.py
> +    def __init__(
this makes sense, it's true that some of the info that's saved is useful. But we probably do not want to save input arguments (contrary to what happens in modules).

So maybe it should still be a `LearnableMixin`?
I need to look at [metaclasses and other fancy modern features](https://docs.python.org/3/reference/datamodel.html#customizing-class-creation) because there might be a way to have something a bit neater like

```python
class MyNetwork(LoadableModule):  # implicitly, save_args=False

    # no need for decorator
    def __init__(...): ...

class LoadableTrainer(LoadableMixin, save_args=False):

    # do stuff
```

And so maybe our base trainer should really be called `LoadableTrainer`.

Also, in `LoadableMixin`, we could rename the `"state"` key to `"modules"` key. And in the trainer we simply need to make models and losses to be `LoadableModuleDict`, and implement a `LoadableOptimDict`. And the serialize function would simply be:

```python
class LoadableTrainer(LoadableMixin, save_args=False):

    def serialize(self):
        state = super().serialize()
        state["optimizers"] = self.optimizers.serialize()
        return state
```

2024-11-11 18:15 UTC, EtienneChollet commented on cassetta/optimizers/__init__.py
> +], __name__, __all__, True)
Awesome! Sounds great :)

2024-11-11 18:36 UTC, balbasty requested changes

2024-11-11 18:36 UTC, balbasty commented on cassetta/io/modules.py
> +            "cassetta.LoadableState": LoadableMixin.__version__,
I know this is me but I am wondering if this should be `"cassetta.LoadableState"` since we now have a class with almost the same name. Maybe `"cassetta.LoadableMixin"`? or just `"cassetta.Loadable"`

2024-11-11 18:36 UTC, balbasty commented on cassetta/io/modules.py
> +            "state": self.state_dict(),
I think it's a mistake that you're saving both `[module.serialize() for module in self]` and `self.state_dict()` as both contain the models weights. I have a feeling you should not be saving `self.state_dict()`.

2024-11-11 18:36 UTC, balbasty commented on cassetta/io/modules.py
> +# loaded_model = LoadableSequential.load('loadable_sequential.pth')
Remove commented code

2024-11-11 18:36 UTC, balbasty commented on cassetta/io/modules.py
> +        }
Same comment as before: you should not be saving `self.state_dict()`.

2024-11-11 18:36 UTC, balbasty commented on cassetta/io/modules.py
> +        }
Same comment as before: you should not be saving `self.state_dict()`.

2024-11-11 18:36 UTC, balbasty commented on cassetta/io/modules.py
> +        # Gather state dict as standard from pytorch optimizer
If we rename "state" to "modules" in `LoadableMixin`, maybe pop the "modules" key here?

2024-11-11 18:36 UTC, balbasty commented on cassetta/io/modules.py
> +        serialized_state["state"] = self.state_dict()
Here it can still be called "state", since it's specific to optimizers

2024-11-11 18:36 UTC, balbasty commented on cassetta/io/modules.py
> +            args = args[1:]
I don't think that's good in case the person set learning rate as a positional (i.e. `Optimizer(model.parameters(), 1e-3)`, rather than `Optimizer(model.parameters(), lr=1e-3)`), because when loading you'll now be calling `Optimizer(1e-3)`, no? Maybe better to replace the parameters with an empty list (`args = [[]] + list(args[1:])`)

2024-11-11 21:58 UTC, EtienneChollet commented on cassetta/io/modules.py
> +        }
Thank you! Fixed in 87e332b

2024-11-11 21:59 UTC, EtienneChollet commented on cassetta/io/modules.py
> +        }
Fixed in 87e332b

2024-11-11 21:59 UTC, EtienneChollet commented on cassetta/io/modules.py
> +# loaded_model = LoadableSequential.load('loadable_sequential.pth')
Nice catch ;). Fixed in 8e6b45b638180f07200543eee2423b826b3b304e

2024-11-11 22:04 UTC, EtienneChollet commented on cassetta/io/modules.py
> +        # Gather state dict as standard from pytorch optimizer
Gotcha. Just as a reminder for myself: you and I talked about this on Teams and agreed that we will just leave it the way it is, and possibly revisit it down the line when we've developed a better workflow/vernacular for cassetta.

2024-11-11 22:08 UTC, EtienneChollet commented on cassetta/io/modules.py
> +            args = args[1:]
Safety first!! Fixed in 671b2c8

2024-11-11 22:09 UTC, EtienneChollet commented on cassetta/io/modules.py
> +        serialized_state["state"] = self.state_dict()
Reminder to myself: see above conversations. Yael and I talked about this on Teams and agreed that we will just leave it the way it is, and possibly revisit this `state` vs. `module` stuff down the line when we've developed a better workflow/vernacular for cassetta

2024-11-12 13:11 UTC, merged